In [4]:
import pandas as pd 
import numpy as np 
from sklearn.impute import SimpleImputer # to fill na values we use the imputer it fills na on multiple columns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OrdinalEncoder # works same as label encoder but on x variables all feature
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
import warnings
warnings.filterwarnings('ignore')


In [5]:
df = pd.read_csv('cars_new.csv')

In [6]:
df.head(2)

symboling normalized-losses         make fuel-type   body-style  \
0          3                 ?  alfa-romero       gas  convertible   
1          3                 ?  alfa-romero       gas  convertible   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   body-style         205 non-null    object 
 5   drive-wheels       205 non-null    object 
 6   engine-location    205 non-null    object 
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object 
 10  engine-size        205 non-null    int64  
 11  horsepower         205 non-null    object 
 12  city-mpg           205 non-null    int64  
 13  highway-mpg        205 non-null    int64  
 14  price              205 non-null    int64  
dtypes: float64(2), int64(5), object(8)
memory usage: 24.2+ KB


In [9]:
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [10]:
df["normalized-losses"].value_counts()

normalized-losses
?      41
161    11
91      8
150     7
134     6
128     6
104     6
85      5
94      5
65      5
102     5
74      5
168     5
103     5
95      5
106     4
93      4
118     4
148     4
122     4
83      3
125     3
154     3
115     3
137     3
101     3
119     2
87      2
89      2
192     2
197     2
158     2
81      2
188     2
194     2
153     2
129     2
108     2
110     2
164     2
145     2
113     2
256     1
107     1
90      1
231     1
142     1
121     1
78      1
98      1
186     1
77      1
Name: count, dtype: int64

In [11]:
df.replace('?',np.nan,inplace =True)

In [19]:
df

symboling normalized-losses         make fuel-type   body-style  \
0            3               NaN  alfa-romero       gas  convertible   
1            3               NaN  alfa-romero       gas  convertible   
2            1               NaN  alfa-romero       gas    hatchback   
3            2               164         audi       gas        sedan   
4            2               164         audi       gas        sedan   
..         ...               ...          ...       ...          ...   
200         -1                95        volvo       gas        sedan   
201         -1                95        volvo       gas        sedan   
202         -1                95        volvo       gas        sedan   
203         -1                95        volvo    diesel        sedan   
204         -1                95        volvo       gas        sedan   

    drive-wheels engine-location  width  height engine-type  engine-size  \
0            rwd           front   64.1    48.8        dohc          130   
1            rwd           front   64.1    48.8        dohc          130   
2            rwd           front   65.5    52.4        ohcv          152   
3            fwd           front   66.2    54.3         ohc          109   
4            4wd           front   66.4    54.3         ohc          136   
..           ...             ...    ...     ...         ...          ...   
200          rwd           front   68.9    55.5         ohc          141   
201          rwd           front   68.8    55.5         ohc          141   
202          rwd           front   68.9    55.5        ohcv          173   
203          rwd           front   68.9    55.5         ohc          145   
204          rwd           front   68.9    55.5         ohc          141   

    horsepower  city-mpg  highway-mpg  price  
0          111        21           27  13495  
1          111        21           27  16500  
2          154        19           26  16500  
3          102        24           30  13950  
4          115        18           22  17450  
..         ...       ...          ...    ...  
200        114        23           28  16845  
201        160        19           25  19045  
202        134        18           23  21485  
203        106        26           27  22470  
204        114        19           25  22625  

[205 rows x 15 columns]

In [22]:
df.isna().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            2
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [23]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower            object
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [25]:
si = SimpleImputer(strategy ="median")
df



symboling normalized-losses         make fuel-type   body-style  \
0            3               NaN  alfa-romero       gas  convertible   
1            3               NaN  alfa-romero       gas  convertible   
2            1               NaN  alfa-romero       gas    hatchback   
3            2               164         audi       gas        sedan   
4            2               164         audi       gas        sedan   
..         ...               ...          ...       ...          ...   
200         -1                95        volvo       gas        sedan   
201         -1                95        volvo       gas        sedan   
202         -1                95        volvo       gas        sedan   
203         -1                95        volvo    diesel        sedan   
204         -1                95        volvo       gas        sedan   

    drive-wheels engine-location  width  height engine-type  engine-size  \
0            rwd           front   64.1    48.8        dohc          130   
1            rwd           front   64.1    48.8        dohc          130   
2            rwd           front   65.5    52.4        ohcv          152   
3            fwd           front   66.2    54.3         ohc          109   
4            4wd           front   66.4    54.3         ohc          136   
..           ...             ...    ...     ...         ...          ...   
200          rwd           front   68.9    55.5         ohc          141   
201          rwd           front   68.8    55.5         ohc          141   
202          rwd           front   68.9    55.5        ohcv          173   
203          rwd           front   68.9    55.5         ohc          145   
204          rwd           front   68.9    55.5         ohc          141   

    horsepower  city-mpg  highway-mpg  price  
0          111        21           27  13495  
1          111        21           27  16500  
2          154        19           26  16500  
3          102        24           30  13950  
4          115        18           22  17450  
..         ...       ...          ...    ...  
200        114        23           28  16845  
201        160        19           25  19045  
202        134        18           23  21485  
203        106        26           27  22470  
204        114        19           25  22625  

[205 rows x 15 columns]

In [26]:
df.iloc[:,[1,11]] # access only column index 1 and 11 

normalized-losses horsepower
0                 NaN        111
1                 NaN        111
2                 NaN        154
3                 164        102
4                 164        115
..                ...        ...
200                95        114
201                95        160
202                95        134
203                95        106
204                95        114

[205 rows x 2 columns]

In [27]:
df.iloc[:,[1,11]] = si.fit_transform(df.iloc[:,[1,11]])

In [28]:
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [29]:
df

symboling normalized-losses         make fuel-type   body-style  \
0            3             115.0  alfa-romero       gas  convertible   
1            3             115.0  alfa-romero       gas  convertible   
2            1             115.0  alfa-romero       gas    hatchback   
3            2             164.0         audi       gas        sedan   
4            2             164.0         audi       gas        sedan   
..         ...               ...          ...       ...          ...   
200         -1              95.0        volvo       gas        sedan   
201         -1              95.0        volvo       gas        sedan   
202         -1              95.0        volvo       gas        sedan   
203         -1              95.0        volvo    diesel        sedan   
204         -1              95.0        volvo       gas        sedan   

    drive-wheels engine-location  width  height engine-type  engine-size  \
0            rwd           front   64.1    48.8        dohc          130   
1            rwd           front   64.1    48.8        dohc          130   
2            rwd           front   65.5    52.4        ohcv          152   
3            fwd           front   66.2    54.3         ohc          109   
4            4wd           front   66.4    54.3         ohc          136   
..           ...             ...    ...     ...         ...          ...   
200          rwd           front   68.9    55.5         ohc          141   
201          rwd           front   68.8    55.5         ohc          141   
202          rwd           front   68.9    55.5        ohcv          173   
203          rwd           front   68.9    55.5         ohc          145   
204          rwd           front   68.9    55.5         ohc          141   

    horsepower  city-mpg  highway-mpg  price  
0        111.0        21           27  13495  
1        111.0        21           27  16500  
2        154.0        19           26  16500  
3        102.0        24           30  13950  
4        115.0        18           22  17450  
..         ...       ...          ...    ...  
200      114.0        23           28  16845  
201      160.0        19           25  19045  
202      134.0        18           23  21485  
203      106.0        26           27  22470  
204      114.0        19           25  22625  

[205 rows x 15 columns]

In [31]:
df.select_dtypes(int) # it will display onlt the integer columns

symboling  engine-size  city-mpg  highway-mpg  price
0            3          130        21           27  13495
1            3          130        21           27  16500
2            1          152        19           26  16500
3            2          109        24           30  13950
4            2          136        18           22  17450
..         ...          ...       ...          ...    ...
200         -1          141        23           28  16845
201         -1          141        19           25  19045
202         -1          173        18           23  21485
203         -1          145        26           27  22470
204         -1          141        19           25  22625

[205 rows x 5 columns]

In [32]:
df.select_dtypes(float)

width  height
0     64.1    48.8
1     64.1    48.8
2     65.5    52.4
3     66.2    54.3
4     66.4    54.3
..     ...     ...
200   68.9    55.5
201   68.8    55.5
202   68.9    55.5
203   68.9    55.5
204   68.9    55.5

[205 rows x 2 columns]

In [34]:
df.select_dtypes(object)

normalized-losses         make fuel-type   body-style drive-wheels  \
0               115.0  alfa-romero       gas  convertible          rwd   
1               115.0  alfa-romero       gas  convertible          rwd   
2               115.0  alfa-romero       gas    hatchback          rwd   
3               164.0         audi       gas        sedan          fwd   
4               164.0         audi       gas        sedan          4wd   
..                ...          ...       ...          ...          ...   
200              95.0        volvo       gas        sedan          rwd   
201              95.0        volvo       gas        sedan          rwd   
202              95.0        volvo       gas        sedan          rwd   
203              95.0        volvo    diesel        sedan          rwd   
204              95.0        volvo       gas        sedan          rwd   

    engine-location engine-type horsepower  
0             front        dohc      111.0  
1             front        dohc      111.0  
2             front        ohcv      154.0  
3             front         ohc      102.0  
4             front         ohc      115.0  
..              ...         ...        ...  
200           front         ohc      114.0  
201           front         ohc      160.0  
202           front        ohcv      134.0  
203           front         ohc      106.0  
204           front         ohc      114.0  

[205 rows x 8 columns]

In [1]:
df["normalized-losses"] =df["normalized-losses"].astype('float')

NameError: name 'df' is not defined

In [36]:
df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower            object
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [42]:
df["horsepower"] =df["horsepower"].astype(float)

In [43]:
df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [44]:
# apply encoding one categorical columns

In [45]:
cat_cols =df.select_dtypes(object).columns
cat_cols

Index(['make', 'fuel-type', 'body-style', 'drive-wheels', 'engine-location',
       'engine-type'],
      dtype='object')

In [46]:
df[cat_cols]

make fuel-type   body-style drive-wheels engine-location  \
0    alfa-romero       gas  convertible          rwd           front   
1    alfa-romero       gas  convertible          rwd           front   
2    alfa-romero       gas    hatchback          rwd           front   
3           audi       gas        sedan          fwd           front   
4           audi       gas        sedan          4wd           front   
..           ...       ...          ...          ...             ...   
200        volvo       gas        sedan          rwd           front   
201        volvo       gas        sedan          rwd           front   
202        volvo       gas        sedan          rwd           front   
203        volvo    diesel        sedan          rwd           front   
204        volvo       gas        sedan          rwd           front   

    engine-type  
0          dohc  
1          dohc  
2          ohcv  
3           ohc  
4           ohc  
..          ...  
200         ohc  
201         ohc  
202        ohcv  
203         ohc  
204         ohc  

[205 rows x 6 columns]

In [47]:
oe = OrdinalEncoder()
df[cat_cols] =oe.fit_transform(df[cat_cols])

In [49]:
df.dtypes

symboling              int64
normalized-losses    float64
make                 float64
fuel-type            float64
body-style           float64
drive-wheels         float64
engine-location      float64
width                float64
height               float64
engine-type          float64
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [50]:
# model building 

In [51]:
x = df.iloc[:,:-1]
y =df.iloc[:,-1]


In [53]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state =1)

In [54]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [55]:
y_pred  = lr.predict(x_test)
y_pred

array([ 6114.11943789,  6899.1299745 ,  5179.12129606,  6534.49022809,
        9125.91144455, 26384.12259969,  7406.15558344,   895.58275157,
        5172.9291232 , 13513.24663171, 15407.85345859, 14421.55136235,
       16418.89788598, 11145.35574554, 16463.66533212, 13896.61774947,
        7335.98228673,  8845.0632645 , 10862.74899523,  7555.18709439,
       11006.99145217,  6830.04912601, 13638.73999814,  6363.9621527 ,
       13732.90563984,  8845.0632645 , 15040.20874209,  6544.19455256,
        4706.60204753,  9314.78618354,  8128.3940468 , 14321.0634702 ,
       25655.82279003, 11987.68138692, 19723.90650907,  6557.53154026,
        8154.91470876, 30658.97297566,  9834.8439003 , 16923.44920496,
        6520.66900847, 20194.14945986,  7692.55861481,  8459.52258636,
        8670.04245903,  7166.21791784, 40486.41308962,  7569.40057796,
       17170.51789287, 18954.92930717, 26190.76513016, 16914.80136249,
       21856.35461232,  6225.96759922, 13090.60124574,  7294.0335782 ,
      

In [56]:
y_pred == y_test

78     False
97     False
151    False
44     False
40     False
       ...  
39     False
110    False
164    False
56     False
176    False
Name: price, Length: 62, dtype: bool

In [61]:
lr.intercept_ # y intercept == c y =mx+c , c= intercept

-64935.113579782475

In [63]:
lr.coef_ # this all are slopes

array([ 5.71727164e+01,  4.76320989e-01, -2.01309566e+02, -6.22705136e+02,
       -1.63712110e+02,  1.88863899e+03,  1.63884484e+04,  7.90632094e+02,
        3.61221503e+02,  2.81207534e+02,  9.82290864e+01, -1.06474945e+01,
        3.08435166e+02, -4.17126915e+02])

In [65]:
lr.score(x_train,y_train),lr.score(x_test,y_test)
# overfitted model

(0.8504229026078213, 0.7964854785429522)

# lasoregression

In [66]:
l1 = Lasso()
l1.fit(x_train,y_train)
l1.score(x_train,y_train),l1.score(x_test,y_test)


(0.8504215478243033, 0.7966615211575689)

In [67]:
l1.coef_

array([ 5.70766693e+01,  4.67141700e-01, -2.01139953e+02, -6.14206970e+02,
       -1.64751649e+02,  1.88558824e+03,  1.63181959e+04,  7.88680118e+02,
        3.61783500e+02,  2.81248690e+02,  9.83193653e+01, -1.05310631e+01,
        3.07274772e+02, -4.15725804e+02])

# hyper parameter tuning

In [72]:
for i in range(100,200):
    l1 = Lasso(alpha = i)
    l1.fit(x_train,y_train)
    print(f"alpha: {i} train: {l1.score(x_train,y_train)} test: {l1.score(x_test,y_test)}")
    

alpha: 100 train: 0.8372483974026499 test: 0.8092040910955615
alpha: 101 train: 0.8369899229541409 test: 0.8092979610738256
alpha: 102 train: 0.8367288785613758 test: 0.8093910017461713
alpha: 103 train: 0.8364651676681871 test: 0.8094832684251523
alpha: 104 train: 0.8361989818307348 test: 0.809574650362481
alpha: 105 train: 0.8359302253870347 test: 0.8096652035299013
alpha: 106 train: 0.8356588978359675 test: 0.8097549282309101
alpha: 107 train: 0.8353849991129143 test: 0.8098438245155561
alpha: 108 train: 0.8351084257059384 test: 0.8099319454841268
alpha: 109 train: 0.8348293842179736 test: 0.8100191840285436
alpha: 110 train: 0.8345477714936768 test: 0.8101055942385992
alpha: 111 train: 0.8342635877040373 test: 0.8101911760417996
alpha: 112 train: 0.8339767222137543 test: 0.8102759813628974
alpha: 113 train: 0.8336873954613211 test: 0.8103599056262563
alpha: 114 train: 0.8333954973355284 test: 0.8104430016665038
alpha: 115 train: 0.8331010276993127 test: 0.8105252695475362
alpha: 11

In [75]:
l1.coef_ # slope which is near to zero this column is not important for the model prediction in our problem

array([  21.00322193,   -0.        , -169.36407648,   -0.        ,
       -393.06257077, 1149.99845398, 2120.82841014,  330.31504682,
        463.48125332,  300.74452902,  115.28035246,   14.21388963,
         35.09289655, -123.89541752])

In [76]:
x_train.columns # normalised losses & fuel type is not important to calculate the car price 

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'body-style',
       'drive-wheels', 'engine-location', 'width', 'height', 'engine-type',
       'engine-size', 'horsepower', 'city-mpg', 'highway-mpg'],
      dtype='object')

In [80]:
l2 = Ridge()
l2.fit(x_train,y_train)
l2.score(x_train,y_train),l2.score(x_test,y_test)


(0.8435840853399225, 0.8075632224690532)

In [81]:
for i in range(1,100):
     l2 = Ridge(alpha = i)
     l2.fit(x_train,y_train)
     print(f"alpha: {i} train: {l2.score(x_train,y_train)} test: {l2.score(x_test,y_test)}")
    
    

alpha: 1 train: 0.8435840853399225 test: 0.8075632224690532
alpha: 2 train: 0.8356695734845094 test: 0.8112192014374253
alpha: 3 train: 0.8296379623431073 test: 0.8129299663310143
alpha: 4 train: 0.8250699092246865 test: 0.8138839096972442
alpha: 5 train: 0.8215093087765016 test: 0.8144682684596011
alpha: 6 train: 0.8186486103834848 test: 0.814843562726523
alpha: 7 train: 0.816288257302081 test: 0.8150880725612083
alpha: 8 train: 0.8142964263180523 test: 0.815244730507158
alpha: 9 train: 0.8125835227290971 test: 0.8153392574436444
alpha: 10 train: 0.8110868722186455 test: 0.8153881483263247
alpha: 11 train: 0.8097614513602517 test: 0.8154025610279506
alpha: 12 train: 0.8085741366835051 test: 0.815390369370157
alpha: 13 train: 0.8075000372738094 test: 0.8153573212892009
alpha: 14 train: 0.8065200924084595 test: 0.8153077294072231
alpha: 15 train: 0.8056194580416448 test: 0.8152449025615432
alpha: 16 train: 0.8047863980733031 test: 0.815171426484327
alpha: 17 train: 0.8040115065187472 te

In [83]:
l2.coef_ # it does not reduce the value of the alpha as zero 

array([ 143.44467168,    0.74117302, -167.76236561, -219.47156508,
       -334.12389693,  486.38089524,  327.22605806,  283.01615782,
        457.94733431,  279.94413044,  117.8073432 ,   22.26339856,
        115.7880488 , -193.94174355])

# elastic net

In [85]:
en = ElasticNet(alpha =1)
en.fit(x_train,y_train)
en.score(x_train,y_train),en.score(x_test,y_test)

(0.7866253599240466, 0.809826481725613)